<a href="https://colab.research.google.com/github/being3iimed/pytorchjourney/blob/main/basicstorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Basics PyTorch**

In [3]:
import torch

In [ ]:
# A scalar (0-dimensional tensor)
scalar = torch.tensor(5)

# 4. same as 4.0 used to indicated floating point number
t1 = torch.tensor(4.)
print("type:", t1.dtype)
print("size:", t1.shape)

In [ ]:
"""
we can  indicate the type for the entered value like this
t1 = torch.tensor(4, dtype=float)
"""
t1 = torch.tensor(2, dtype=torch.float32)
t1.dtype

In [ ]:
# A vector (1-dimensional tensor)
vector = torch.tensor([1, 2, 3])
t2 = torch.tensor([1, 2, 3, 9.]) # a vector of float
print("type:", t2.dtype)
print("size:", t2.shape)

In [ ]:
# A matrix (2-dimensional tensor)
matrix = torch.tensor([[1, 2], [3, 4]])

In [ ]:
# 3x2 matrix filled with zeros
z = torch.zeros(3, 2)
print(z)
print(z.dtype)

# 5x3 matrix filled with ones
ones = torch.ones((2, 3), dtype=torch.float32)
print(ones)

In [ ]:
# A 3-dimensional tensor
tensor3d = torch.rand(2, 3, 4)  # Random values in a 2x3x4 tensor
print(tensor3d)

# a 2-dimensional array/tensor
"""
The tensors must be correctly shaped,
meaning the matrices within an n-dimensional array must align with the row length of that array.
"""
t4 = torch.tensor([
                [[1, 3],
                 [0, 6],
                 [2, 1]],
                [[1, 3],
                 [2, 1],
                 [0, 6]]])
print(t4.dtype)
print(t4.shape) # size of it, basically number of D for the created tensor
t4


In [83]:
"""
'torch.manual_seed()'

Random weight initialization is essential for effective training in neural networks,
while using a seed makes these random processes reproducible,
ensuring consistent results across multiple runs of the same experiment.
"""
torch.manual_seed(42)
"""
42 here is arbitrary, and any integer (e.g., 0, 1234, 2024)
would serve the same purpose. As long as the seed value is the same across run.
"""
rand1 = torch.rand(2, 4)
rand2 = torch.rand(2, 4)

torch.manual_seed(42)
rand3 = torch.rand(2, 4)
rand4 = torch.rand(2, 4)

rand1, rand2, rand3, rand4

(tensor([[0.3126, 0.3791, 0.3087, 0.0736],
         [0.4216, 0.0691, 0.2332, 0.4047]]),
 tensor([[0.2162, 0.9927, 0.4128, 0.5938],
         [0.6128, 0.1519, 0.0453, 0.5035]]),
 tensor([[0.3126, 0.3791, 0.3087, 0.0736],
         [0.4216, 0.0691, 0.2332, 0.4047]]),
 tensor([[0.2162, 0.9927, 0.4128, 0.5938],
         [0.6128, 0.1519, 0.0453, 0.5035]]))

Tensor Operations

In [ ]:
a = torch.tensor([1, 5, 4, 6])
b = torch.tensor([6, 2, 1, 0])

# Element-wise addition
c = a  + b
c

In [ ]:
ones = torch.ones(2, 3)
print(ones)
twos = torch.ones(2, 3) * 2
print(twos)

#The size of tensor a (4) must match the size of tensor b
threes = ones + twos
print(threes)

In [5]:
ones = torch.zeros(2, 2) + 1
twos = torch.ones(2, 2) * 2
threes = (torch.ones(2, 2) * 7 - 1) / 2
fours = twos ** 2
sqrt2s = twos ** 0.5

print(ones)
print(twos)
print(threes)
print(fours)
print(sqrt2s)

tensor([[1., 1.],
        [1., 1.]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[3., 3.],
        [3., 3.]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[1., 1.],
        [1., 1.]])


In [ ]:
# Dot product
"""
NOTE: Dot product takes two equal-length sequences of numbers
(usually coordinate vectors or sequences of numbers), and returns a single number.
"""
dot_product = torch.dot(a, b)
dot_product

In [ ]:
# Matrix multiplication
A = torch.rand(2, 3)
B = torch.rand(3, 2)
matmul = torch.mm(A, B)
matmul

In [4]:
# common functions
a = torch.rand(2, 4) * 2 - 1
print('Common functions:')
print(torch.abs(a))
print(torch.ceil(a))
print(torch.floor(a))
print(torch.clamp(a, -0.5, 0.5))

Common functions:
tensor([[0.9031, 0.8921, 0.2652, 0.5969],
        [0.4200, 0.2885, 0.0418, 0.1587]])
tensor([[1., -0., 1., 1.],
        [-0., 1., -0., 1.]])
tensor([[ 0., -1.,  0.,  0.],
        [-1.,  0., -1.,  0.]])
tensor([[ 0.5000, -0.5000,  0.2652,  0.5000],
        [-0.4200,  0.2885, -0.0418,  0.1587]])


Autograd (Automatic Differentiation) / derivatives

In [ ]:
x = torch.tensor(2.)
y = torch.tensor(3., requires_grad=True)
z = torch.tensor(4.5, requires_grad=True)
x, y, z

In [ ]:
# Arithmetic operations
r = x + y * z

#compute the derivatives/gradient, we can call the .backward
r.backward()

In [ ]:
# Display gradients
print('dr/dx:', x.grad)
print('dr/dy:', y.grad)
print('dr/dz:', z.grad)

In [ ]:
x = torch.tensor(2.0, requires_grad=True)
y = x ** 2
y.backward()  # Compute gradients

print(x.grad)  # Gradient of y with respect to x